# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20160923_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='headImg',
            field=models.FileField(default=django.utils.timezone.now, upload_to='./upload/'),
            preserve_default=False,
        ),
    ]
